baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Bertrand Nau | Fullstack Developer / DevOps'
theme: 'hugo-profile'
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Bertrand Nau"
  namecolor: ffc107
  profession: "Fullstack Developer / DevOps"
  github: "https://github.com/bnau"
  linkedin: "https://linkedin.com/in/bertrand-nau"
  twitter: "https://twitter.com/bertrand_nau"

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "mailto:naubertrand@gmail.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Profile, a passionate web developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 85
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Takima"
      role: "Senior Fullstack Developer"
      startdate: January 2020
      enddate: April 2020
      featuredpoints:
        - point: Development of Deadlock, one of the most promising internal projects of the company
        - point: Code Reviews
        - point: Establishment of the frontend tests
        - point: Teaching and writing materials for a two months training course on advanced programming techniques
        - point: Interviewing of graduate Developers
      stack:
        - lang: Java
        - lang: Spring Boot
        - lang: Kotlin
        - lang: Rust
        - lang: React
        - lang: Kubernetes
        - lang: GCP
        - lang: Gitlab CI
    - company: "KleeGroup"
      role: "Fullstack Developer"
      startdate: October 2014
      enddate: November 2019
      featuredpoints:
        - point: Technical work on multiple Web Business Applications
        - point: Leading Developers Teams - up to 4 people
        - point: Coaching of Junior Developers
        - point: Architectural Documents Writing
        - point: Integration of new technologies in the Company (Python, Gradle)
        - point: Contribution to Internal Frameworks
      stack:
        - lang: Java
        - lang: J2EE
        - lang: Spring
        - lang: Python
        - lang: Javascript
        - lang: Typescript
        - lang: Angular
        - lang: React
        - lang: PostgreSQL
        - lang: MySQL
        - lang: Oracle
        - lang: Jenkins
        - lang: ElasticSearch
      # Ajouter les missions
    - company: "Renault"
      role: "Intern"
      startdate: March 2014
      enddate: September 2014
      featuredpoints:
        - point: Conception and realization of a web application demonstrator for the calculation of quality indicators.
        - point: Studies of the client's needs and the possible solutions.
      stack:
        - lang: Java
        - lang: J2EE
        - lang: JBoss
        - lang: Oracle
    - company: "Endress+Hauser"
      id: "endress"
      role: "Intern"
      startdate: May 2013
      enddate: September 2013
      featuredpoints:
        - point: Conception and realization of a fieldbus communications analyzer.
        - point: Study of the communication frames.
        - point: Analysis of the architecture of the application.
      stack:
        - lang: C#
    - company: "Areva"
      role: "Intern"
      startdate: May 2012
      enddate: August 2012
      featuredpoints:
        - point: Development of a graphical user interface to realize sustainability studies.
      stack:
        - lang: VBA
        - lang: Access
    - company: "D3E Electronique"
      id: "d3e"
      role: "Intern"
      startdate: May 2011
      enddate: August 2011
      featuredpoints:
        - point: Development of an intranet website to computerize the customer's followed up.
      stack:
        - lang: PHP
        - lang: MySQL
        - lang: Apache

  # Education
  disable_education: false
  education:
    - degree: "Engineer's degree"
      branch: "Information Technology"
      university: "École des Mines de Douai"
      startedyear: "2010"
      graduation: "2014"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  disable_contact: true

security:
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^asciidoctor$
